### PR TITLE
Compute sampling rate for antenna sensors

### PR DESCRIPTION
**Pull request by bmerry**
The rate is set to min(2s, dump_rate/2) (using the min dump rate if
there are multiple sdp.vis streams).

Closes SPR1-641.

### CODE REVIEW

**Review by ludwigschwardt — CHANGES_REQUESTED** [review]
The only suggestion is to rename 'antenna' sensors to 'position' sensors, since CBF pointing is also sampled this way and other antenna sensors like 'm000_activity' are not.

**Comment by bmerry** [comment]
Good point. See if you're happy with the new version.

**Review by ludwigschwardt — APPROVED** [review]
Thanks!

**Review by ludwigschwardt — COMMENTED** [review]
Oh wait - question - why not a default of 4 seconds (for 8-second dumps), or is that too coarse for positions (I guess)?

**Comment by bmerry** [comment]
I think the motivation for a max of 2s was that beyond that we get diminishing returns, and some users might want the finer granularity for analysis other than imaging.

**Comment by ludwigschwardt** [comment]
Good point, happy then.

**Pull request merged**
